# NumPy: Array Basics

Core NumPy array creation and manipulation.

**Covers:**
- Array creation and basic attributes
- Unique values
- Random sampling

In [2]:
#Day3
import numpy as np

In [3]:
v1 = np.array(['blue','red','green','black', 'red','yellow','pink','black'])

In [4]:
#to identify the unique element
print(np.unique(v1))

['black' 'blue' 'green' 'pink' 'red' 'yellow']


In [9]:
#generate sample
#rand  --> generates samples that follows uniform distribution. 
#randn -->generates samples that follows normal distribution.
m1 = np.random.rand(3,2)
m2 = np.random.randn(4,3)

In [73]:
print(m1,"\n",m2)

[[3.45       0.47002736]
 [0.97995017 0.61955498]
 [0.55859575 0.4542456 ]] 
 [[-8.93618638e-01 -9.89749788e-01  1.18335769e+00]
 [-8.12070376e-01 -5.24376474e-01 -3.19006252e-01]
 [ 3.80352199e-01 -4.55261575e-02  5.01541085e-01]
 [-9.14717917e-04  3.41168719e-01  5.25034012e-01]]


In [33]:
#mean

m= np.mean(m1)
#resrict the decimal 
print(f"Mean =  {m:.2f}".format(m))
print(np.mean(m2))

Mean =  0.68
-0.05448405863341777


In [23]:
#standard deviation 
print(np.std(m1))

0.22375555894715582


In [24]:
#max
#min
print(np.max(m1))
print(np.min(m2))

0.9914312785774421
-0.9897497881495148


In [26]:
#Access data
#indexing
#slicing
v2 = np.random.randn(19)

In [27]:
print(v2)

[-1.33811503  0.62321455 -2.46489013  0.79521176  0.89765983 -1.22217216
  1.19496992  0.37495484 -1.39203245 -0.84980641 -0.11439548 -1.0437652
 -0.98356824  1.71149237 -0.06732848 -0.6984422   0.08296358 -1.22864061
 -0.3942394 ]


In [29]:
print(v2[0])

-1.33811503199562


In [30]:
print(v2[0:5:2])

[-1.33811503 -2.46489013  0.89765983]


In [31]:
v2[0]= 234.618
#array is mutable
print(v2)

[ 2.34618000e+02  6.23214555e-01 -2.46489013e+00  7.95211757e-01
  8.97659833e-01 -1.22217216e+00  1.19496992e+00  3.74954838e-01
 -1.39203245e+00 -8.49806410e-01 -1.14395477e-01 -1.04376520e+00
 -9.83568238e-01  1.71149237e+00 -6.73284772e-02 -6.98442204e-01
  8.29635835e-02 -1.22864061e+00 -3.94239401e-01]


In [36]:
#replacing single and spicified index value
v2[0:5:2] = [12.5,13.5,14.5]
print(v2)

[12.5         0.62321455 13.5         0.79521176 14.5        -1.22217216
  1.19496992  0.37495484 -1.39203245 -0.84980641 -0.11439548 -1.0437652
 -0.98356824  1.71149237 -0.06732848 -0.6984422   0.08296358 -1.22864061
 -0.3942394 ]


In [37]:
print(m1[0,1])

0.470027363047129


In [40]:
print(m1[0:2,0:2])

[[0.99143128 0.47002736]
 [0.97995017 0.61955498]]


In [42]:
m1[0,0] = 3.45
print(m1)

[[3.45       0.47002736]
 [0.97995017 0.61955498]
 [0.55859575 0.4542456 ]]


In [43]:
m3 = np.array([[100,200],[300,400]])
print(m3)

[[100 200]
 [300 400]]


In [45]:
#change the elements of first row ---- 1000 2000
sub=m3[0:1,0:2] = [1000,2000]
print(sub)

[1000, 2000]


In [49]:
#By default any changes done to sub matrix will refelect the orginal matrix as well
su = m3[0:1,0:2]
su[0] = 1000
print(su)

[[1000 1000]]


In [50]:
m4 = np.array([[1,2],[3,4]])
print(m4)

[[1 2]
 [3 4]]


In [57]:
#IF we change the data it will not refelct in the orignal matrix ---.copy()
s1 = m4[1:2,0:2].copy()
print(s1)

[[3 4]]


In [62]:
s1[:] = 100
print(s1)
print()
print(m4)

[[100 100]]

[[1 2]
 [3 4]]


In [64]:
#save single np array to a file ---.npy
#save mutiple np arrays to a file ---.npz
np.save('array1',m1) #save method is meant for saving single array to a .npy file
np.savez('array2',f1 = v1,f2 = m1, f3 =m2)

In [67]:
#load ---- is used to retrieve contents from npy and npz files
data1 = np.load('array1.npy')
print(data1)

[[3.45       0.47002736]
 [0.97995017 0.61955498]
 [0.55859575 0.4542456 ]]


In [68]:
data2 = np.load('array2.npz')
print(data2)

NpzFile 'array2.npz' with keys: f1, f2, f3


In [72]:
print(data2['f1'])
print(data2['f2'])
print(data2['f3'])

['blue' 'red' 'green' 'black' 'red' 'yellow' 'pink' 'black']
[[3.45       0.47002736]
 [0.97995017 0.61955498]
 [0.55859575 0.4542456 ]]
[[-8.93618638e-01 -9.89749788e-01  1.18335769e+00]
 [-8.12070376e-01 -5.24376474e-01 -3.19006252e-01]
 [ 3.80352199e-01 -4.55261575e-02  5.01541085e-01]
 [-9.14717917e-04  3.41168719e-01  5.25034012e-01]]


In [ ]:
#Assignment
#1. Create two numpy arrays by name temperatures and rainfall containing the daily high temeratures and daily rainfall amount for 365 days. Calculate the mean, standard deviation, min, max for both temperatures and rainfall arrays.
#2. Identify the no. of days with temperatures above 30 degrees
#3. Identify the no . of days with no rainfall.
#4. Assume each month has 30 or 31 days. Calulate the average temperature and total rainfall for each month.