# Python Fundamentals: Modules, Packages & NumPy Intro

How Python modules/imports work, plus a first look at NumPy arrays.

**Covers:**
- Creating and importing a custom module (`first.py`)
- NumPy basics: `np.array`, vectors vs. matrices, `.T` (transpose)
- Array creation helpers: `arange`, `reshape`, `zeros`, `ones`, `eye`

In [22]:
#packages and modules
#module -------.py file
#Packages ------ directory with ___init___.py

In [ ]:
%%writefile first.py
v = "Hello from the first module!"


In [23]:
#use contents of files other in this file
#if the file is python then only we can use that file not ipynb 
#in jupyter notebook or colab we can dowlaod the same file ipynb into py to import module

# to print or access the data first step would be
# import [filename]
# to access filenam.variable name
# to access particular data then ---->  from [filename] import [data]
# to access the data as ---->  from [filename] import [data] as new_variable_name
from first import v as d

In [24]:
print(d)

10


In [25]:
#Numpy
#used for - arrays, numerical data, linear algebar  (used for advace mathamatics)
#scaler - one row one coloum --> 1*1
#vector - single row multiple cloum or multiple row single colun --> 1*n or n*1
#matrics - both multiple --> m*n
#tensors - above 2d matrics -->m*n*p
import numpy as np

In [26]:
print(np.cos(np.pi))

-1.0


In [27]:
print(np.sqrt(9))

3.0


In [28]:
print(np.log(np.exp(5)))

5.0


In [29]:
print(np.tan(5))

-3.380515006246586


In [30]:
#creating arrays
#from list
#create a vector
vec = np.array([1,2,3,4,5])
print(type(vec))

<class 'numpy.ndarray'>


In [31]:
#create a matrix
#multiple list --> syntax [[],[]] 
mat = np.array([[1,2,3,4],[5,6,7,8]])
print(type(mat))


<class 'numpy.ndarray'>


In [32]:
print(mat)

[[1 2 3 4]
 [5 6 7 8]]


In [33]:
#Transpose --> interchanging the rows with colum or vica vesa
# variable_name.T
'''
before
[[1 2 3 4]
 [5 6 7 8]]
after
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
'''
print(mat.T)


[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [34]:
#Other method to create array
#arange ---- create a vector within specified values
#arrange ----.arange(start,end,step)
v1 = np.arange(0,11,1)

In [35]:
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [36]:
#converting vector of arrange to matrix
#using reshape(have to check the size is prime or not if yes then we can't do ) -- > 

print(v1.reshape(11,1))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [37]:
v2 = np.arange(0,12,1)
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
#.reshape(m,n)
print(v2.reshape(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [39]:
#all the metrix element is zero or one -- .ones(5,5) or .ones[5,5]
m1 = np.zeros([5,3])
print(m1)
m2 = np.ones((5,5))
print(m2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
#eye metrix --- all the daigonal is one and it's square matrix
m3 = np.eye(4)
print(m3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
#Assingment 
#1. Create two vectore with elements 1 to 5 and 3 to 7 where 5 and 7 are inclusive.Perform add, sub, mul, div
#2. Create two vectors of different lenghs and note the performances of add, sub, mul, div of the vectors
#3. Create two matrics of same size and apply the arithmetic operators and note the bheaviour of data. Also try the operations on matrices of different sizes. 